name: Linux Build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Set up Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.5

      - name: Install Haxe libraries
        run: |
          haxelib --always install hxcpp 
          haxelib --always install fuzzaldrin

      - name: Compile project
        run: haxe build.hxml

      - name: Debug output
        run: ls -la export/haxeCompileU

      - name: Upload compiled artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: Linux64_HxCompileU
          path: export/haxeCompileU
