
name: Linux (Debian) Build
on:
  push:
jobs:
  build:
    name: Linux (Debian) Build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Pulling the new commit
        uses: actions/checkout@v4.1.7
      - name: Setting up Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.5
      - name: Installing/Updating libraries
        run: |
          haxelib --always install hxcpp 
        shell: cmd
      - name: Building HxCompileU
        run: |
          haxe build.hxml
      - name: Uploading artifact (entire build)
        uses: actions/upload-artifact@v4.3.4
        with:
          name: Linux64_HxCompileU
          path: export/haxeCompileU